### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [012to/web_app_1#62]
@012to 
お疲れ様です！

こちらMVPリリースレビューになります！
### 技術
- `app/controllers/posts_controller.rb`の`update`アクションで使用している`@post`は**current_userに紐づいているpostでなければ更新できない**ようにしてあげると良さそうです。
- `app/controllers/users_controller.rb`に記載してある`update_notification_settings`アクションはコントローラーではなく,helperやmodelにメソッドとして切り出して呼び出すようにしてあげても良さそうに思いました。

### ユーザビリティ
さまざまな場所にCSSで動きがついているので、ユーザーから見ると飽きないユーザビリティになっているかと思いました。
ユーザビリティに関しては、現状気になる箇所はなかったのでそのまま開発していただいていいかと思います。

以上です！

READMEに書かれている内容はしっかり実装できているかと思います。
LGTMです！

上記の内容を本リリース実装するタスクに組み込み、スケジュールを立ててみてください。

スケジュール決まりましたら共有をお願いできればと思います。

また上記レビューに関して、質問などありましたらスレッドに記載いただいてご連絡ください！

**Comment by 012to** [comment]
レビューいただきありがとうございます。
新たにissueとスケジュールを作成しました。
5/2を目標に本リリースができるよう、進めていきたいと思います！
[GitHub Projects (開発スケジュール)](https://github.com/users/012to/projects/3/views/1)

**Comment by 012to** [comment]
**現在のつまりポイント**

- 検索機能
一旦Autocompleteの実装はできたが
項目の出力の仕方が微妙...迷走中


- レコメンド機能実装のイメージがあいまい
お気に入りした投稿取得(実装済み)。
ビューカウントにより、投稿の閲覧数取得。
両者の投稿から多いタグを抽出。
関連の強い投稿をマイページに掲載する。

---
**聞きたいこと**

「今後フロントエンドに興味がある」と面談でも言いたいが
今TailwindCSS, Stimulus, Turboくらいしか使えていない。

Javascript, Reactとかは一旦自己学習でいいか？
本リリースにも組み込んだほうが良いか？

buildの方法が違ってくる、JavascriptとTurboの相性もあまりよくない
根本的に変えなければいけないので大変...(?)
